controllers:
    resource: ../src/Controller/
    type: attribute

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /index.html
        permanent: true
